name: Sort HttpsExclusions

on:
  push:
    branches:
      - master
    paths:
      - "**/*.txt"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.txt"

jobs:
  bank:
    name: Check that bank.txt is sorted
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v4
      - name: Run sort
        run: LC_ALL=C sort exclusions/banks.txt -o exclusions/banks.txt
        shell: bash
      - name: Remove last empty line
        run: truncate -s-1 exclusions/banks.txt
        shell: bash
      - name: Run git diff to detect the ordering issue
        run: |
          ! git diff --stat | grep -E "[A-Za-z0-9-]+\.txt"
        shell: bash